feat : 메인페이지 UI 구현
TecherePart2/frontend-repo pull request #10
Opened 2023-03-29 12:34 UTC by bicco2

## 추가한 기능 설명
- 메인 페이지 작성 및 애니메이션 적용
- 메인 페이지 하단 무한 스크롤 구현'

<br>
## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-03-30 06:37 UTC, sangminlee98 requested changes
고생하셨습니다!
수정사항만 다시 수정 후 PR 올리시면 다시 확인하고 Approve 하겠습니다!
(현재 develop 브랜치도 다시 pull받아서 최신화 시켜주세요!)

2023-03-30 06:37 UTC, sangminlee98 commented on components/cardComponent/index.tsx
> +export default function cardComponent({ props }: any) {
해당 컴포넌트 위에 props의 타입을 정의해 주셨는데 any로 사용하신 것 같아요!
PropsData 타입으로 수정해주셔도 될 것 같습니다!

2023-03-30 06:37 UTC, sangminlee98 commented on components/cardComponent/index.tsx
> +  }
호버했을때 opacity값은 0.8로 통일하는게 좋을 거 같아요!

2023-03-30 06:37 UTC, sangminlee98 commented on pages/api/study/1.ts
> +}
요기는 추후에 기능개발할 때 백엔드 API 명세서에 맞춰서 수정하면 될 것 같아요!
나중에 같이 해봐요 🙂

2023-03-30 06:37 UTC, sangminlee98 commented on pages/home/styled.ts
스타일 파일명은 "styles.tsx"로 통일해주세요!

2023-03-30 11:31 UTC, Leeseunghwan7305 reviewed
애니메이션이랑 무한스크롤 어려울꺼같았는데 너무 잘하신거같아요 !
수고많으셨습니다 !

2023-03-30 11:31 UTC, Leeseunghwan7305 commented on hooks/scrollHook.tsx
> +export default useScrollFadeIn;
많이 배워가영 손민수하겠습니다.

2023-03-30 11:31 UTC, Leeseunghwan7305 commented on pages/home/index.tsx
> +        <Button onClick={() => console.log("sdaf")}>
console.log 지워주세요 !

2023-03-30 11:31 UTC, Leeseunghwan7305 commented on pages/home/index.tsx
> +          둘러보기 &nbsp; &gt;{" "}
이것두 지워주세요 !

2023-03-30 11:31 UTC, Leeseunghwan7305 commented on pages/home/styled.ts
> +  word-break: keep-all;
keep-all을 하면 어떻게 되는건가요?

2023-03-30 13:22 UTC, bicco2 commented on pages/home/styled.ts
> +  word-break: keep-all;
줄바꿈 관련 속성인데 keep-all은 단어 단위로 줄바꿈이 됩니다!

2023-03-31 09:20 UTC, sangminlee98 approved these changes
수정사항 잘 적용된 것 같아요!
고생하셨습니다 🙂

2023-03-31 09:26 UTC, merged