채팅창 UI 구현
TecherePart2/frontend-repo pull request #6
Opened 2023-03-25 19:25 UTC by Leeseunghwan7305

## 추가한 기능 설명

<br>
<img width="1502" alt="스크린샷 2023-03-26 오전 4 24 48" src="https://user-images.githubusercontent.com/78102507/227737356-63c78855-e155-4690-b804-4f57dca55d62.png">

## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-03-27 16:07 UTC, sangminlee98 requested changes
고생하셨습니다!
전체적으로 코드를 재사용성 고려해서 잘 짜신 것 같아요!
console.log같은 코드만 지워주시고 다시 PR 날려주시면 될 것 같아요!

2023-03-27 16:07 UTC, sangminlee98 commented on components/chatNav.tsx
> +  }, [router.asPath]);
혹시 useRouter의 asPath를 사용해서 컴포넌트를 구분해주셨군요! 
useLocation의 pathname으로도 가능할 것 같아요!

2023-03-27 16:07 UTC, sangminlee98 commented on components/myMessage.tsx
> +  console.log(clock);
console.log()는 지워주셔도 될 것 같아요!

2023-03-27 16:07 UTC, sangminlee98 commented on components/otherMessage.tsx
> +  console.log(clock);
console.log()는 지워주셔도 될 것 같아요!

2023-03-27 16:07 UTC, sangminlee98 commented on components/roomInformation.tsx
> +`;
반응형으로 태블릿,모바일 사이즈일때는 absolute로 되는거 너무 좋은것 같아요!

2023-03-29 12:59 UTC, bicco2 commented on components/roomTitle.tsx
> +  };
승환님 14번째 줄에 setToggle()로 어떤 기능을 위한 건가요??

2023-03-30 09:26 UTC, Leeseunghwan7305 commented on components/chatNav.tsx
> +  }, [router.asPath]);
그런 방법도 있었군요 ! 참고하겠습니다 !

2023-03-30 09:29 UTC, Leeseunghwan7305 commented on components/myMessage.tsx
> +  console.log(clock);
아 깜빡했네요 ..!
지웠습니다 !

2023-03-30 09:29 UTC, Leeseunghwan7305 commented on components/otherMessage.tsx
> +  console.log(clock);
아 깜빡했네요 ..!
지웠습니다 ! 22

2023-03-30 09:30 UTC, Leeseunghwan7305 commented on components/roomInformation.tsx
> +`;
하하 감사합니당 :)

2023-03-30 09:36 UTC, Leeseunghwan7305 commented on components/roomTitle.tsx
> +  };
<img width="464" alt="스크린샷 2023-03-30 오후 6 35 33" src="https://user-images.githubusercontent.com/78102507/228794781-4ec0d627-7dec-407f-b1f7-5deb21a22b1a.png">

<img width="794" alt="스크린샷 2023-03-30 오후 6 32 44" src="https://user-images.githubusercontent.com/78102507/228794075-bcf8b4c4-b4b6-4a41-8f26-e82635148b61.png">

채팅방 오른쪽 사이드바를 접었다 펼칠수있어야하는데 그떄 사용할 toggle데이터를 전역으로해서 호출한거입니다 !

2023-03-30 09:46 UTC, Leeseunghwan7305 commented on components/chatNav.tsx
> +                  src={currentLocation === link.path ? link.on : link.off}
next없이 react를 쓸떄는 useMatch라는 훅을 이용하면 편했는데 next에서는 useMatch가 없어서 이 방식으로 로직을 짜봤어요 !
이렇게 하는것도 해보니까 좋은것같습니다 !

2023-03-31 10:07 UTC, sangminlee98 requested changes
수정 부탁드립니다!

2023-03-31 10:25 UTC, sangminlee98 approved these changes
확인했습니다! 고생하셨어요🙂

2023-03-31 10:26 UTC, merged